### ISSUE TITLE
Strip spaces from meal classification

### ISSUE THREAD

**Issue by chk1** [chk1/stw2openmensa#12]
CI throws a (caught) error for Python 3.x tests:

```
Processing "mensa_steinfurt.xml" Conversion of "mensa_steinfurt.xml" failed: 'vgn '
Traceback (most recent call last):
  File "parser.py", line 208, in <module>
    status = StudentenwerkToOpenmensa(config.BASE_URL, config.OUT_DIR, config.USER_AGENT, filename)
  File "parser.py", line 152, in StudentenwerkToOpenmensa
    for foodicon in foodicons:
  File "parser.py", line 70, in <lambda>
    fis = map(lambda x: config.CLASSIFICATION[x.lower()], fis)
KeyError: 'vgn '
```

`vgn ` should be `vgn` (without spaces) to match an item in the classification list

https://github.com/chk1/stw2openmensa/blob/master/config.py#L68

Code change somewhere here https://github.com/chk1/stw2openmensa/blob/master/parser.py#L69

**Comment by gfranco93** [comment]
Im on it

**Comment by chk1** [comment]
Thank you!
